# Generated by Django 2.0.6 on 2018-06-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='pc',
            new_name='precio_compra',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='pv',
            new_name='precio_venta',
        ),
    ]
